package org.fisk.swim.todo;

import java.sql.Connection;
import java.sql.SQLException;

final class TodoDb {
    private TodoDb() {
    }

    static void initialize(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists todo_projects (
                    id bigint generated by default as identity primary key,
                    name text not null,
                    name_lc text not null unique,
                    archived integer not null default 0,
                    created_at text not null,
                    updated_at text not null
                )
                """);
        execute(connection, """
                create table if not exists todo_items (
                    id bigint generated by default as identity primary key,
                    project_id bigint,
                    title text not null,
                    body_text text,
                    status text not null default 'open',
                    priority integer not null default 0,
                    due_at text,
                    created_at text not null,
                    updated_at text not null,
                    completed_at text
                )
                """);
        execute(connection, """
                create table if not exists todo_tags (
                    name text primary key,
                    name_lc text not null unique,
                    color text
                )
                """);
        execute(connection, """
                create table if not exists todo_item_tags (
                    todo_id bigint not null,
                    tag_name text not null,
                    primary key (todo_id, tag_name)
                )
                """);
        execute(connection, "alter table todo_projects add column if not exists name_lc text");
        execute(connection, "alter table todo_projects add column if not exists archived integer not null default 0");
        execute(connection, "alter table todo_items add column if not exists body_text text");
        execute(connection, "alter table todo_items add column if not exists priority integer not null default 0");
        execute(connection, "alter table todo_items add column if not exists due_at text");
        execute(connection, "alter table todo_items add column if not exists completed_at text");
        execute(connection, "alter table todo_tags add column if not exists name_lc text");
        execute(connection, "alter table todo_tags add column if not exists color text");
        execute(connection, "create index if not exists idx_todo_items_project on todo_items(project_id)");
        execute(connection, "create index if not exists idx_todo_items_status on todo_items(status)");
        execute(connection, "create index if not exists idx_todo_item_tags_tag on todo_item_tags(tag_name)");
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (var statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
