package org.fisk.swim.plugins.email;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.fisk.swim.mail.MailAccountSummary;
import org.fisk.swim.mail.MailDraft;
import org.fisk.swim.mail.MailMessageDetail;
import org.fisk.swim.mail.MailSnapshot;
import org.fisk.swim.mail.MailThreadPage;
import org.fisk.swim.mail.MailThreadSummary;

final class MailDb {
    record MessageHydrationTarget(long messageId, long threadId, String accountId, String folderName, String internetMessageId) {
    }

    record StoredMessage(
            long id,
            String accountId,
            String threadKey,
            String folderName,
            String subject,
            String fromName,
            String fromEmail,
            String toSummary,
            String sentAt,
            String receivedAt,
            String snippet,
            boolean unread) {
        String effectiveTimestamp() {
            if (receivedAt != null && !receivedAt.isBlank()) {
                return receivedAt;
            }
            if (sentAt != null && !sentAt.isBlank()) {
                return sentAt;
            }
            return "";
        }

        String participants() {
            String from = fromName != null && !fromName.isBlank() ? fromName : fromEmail;
            if (from == null || from.isBlank()) {
                from = "(unknown)";
            }
            if (toSummary == null || toSummary.isBlank()) {
                return from;
            }
            return from + " -> " + toSummary;
        }
    }

    private MailDb() {
    }

    static void initialize(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists accounts (
                    id text primary key,
                    name text not null,
                    protocol text not null,
                    host text,
                    port integer,
                    username text,
                    password_env text,
                    folder text,
                    ews_url text,
                    domain text,
                    auth_type text,
                    updated_at text not null
                )
                """);
        execute(connection, """
                create table if not exists threads (
                    id bigint generated by default as identity primary key,
                    account_id text not null,
                    folder_name text,
                    subject text,
                    participants text,
                    snippet text,
                    last_message_at text,
                    unread_count integer not null default 0,
                    message_count integer not null default 0
                )
                """);
        execute(connection, """
                create table if not exists messages (
                    id bigint generated by default as identity primary key,
                    account_id text not null,
                    thread_id integer,
                    thread_key text,
                    internet_message_id text,
                    folder_name text,
                    subject text,
                    from_name text,
                    from_email text,
                    to_summary text,
                    sent_at text,
                    received_at text,
                    snippet text,
                    body_text text,
                    is_read integer not null default 0
                )
                """);
        execute(connection, """
                create table if not exists tags (
                    name text primary key,
                    color text
                )
                """);
        execute(connection, """
                create table if not exists tag_rules (
                    id bigint generated by default as identity primary key,
                    tag_name text not null,
                    field_name text not null,
                    contains_value text not null
                )
                """);
        execute(connection, """
                create table if not exists message_tags (
                    message_id integer not null,
                    tag_name text not null,
                    primary key (message_id, tag_name)
                )
                """);
        execute(connection, """
                create table if not exists account_sync_state (
                    account_id text primary key,
                    last_sync_at text,
                    status_message text not null default '',
                    backfill_complete integer not null default 0
                )
                """);
        execute(connection, "alter table messages add column if not exists thread_key text");
        execute(connection,
                "alter table account_sync_state add column if not exists backfill_complete integer not null default 0");
        execute(connection,
                "create unique index if not exists idx_messages_account_message_id on messages (account_id, internet_message_id)");
    }

    static void syncAccounts(Connection connection, EmailAccountsConfig config) throws SQLException {
        execute(connection, "delete from accounts");
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into accounts (
                    id, name, protocol, host, port, username, password_env, folder, ews_url, domain, auth_type, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """)) {
            for (EmailAccountConfig account : config.accounts()) {
                statement.setString(1, account.normalizedId());
                statement.setString(2, account.displayName());
                statement.setString(3, account.normalizedProtocol());
                statement.setString(4, account.host());
                if (account.port() == null) {
                    statement.setNull(5, java.sql.Types.INTEGER);
                } else {
                    statement.setInt(5, account.port());
                }
                statement.setString(6, account.username());
                statement.setString(7, account.passwordEnv());
                statement.setString(8, account.folder());
                statement.setString(9, account.ewsUrl());
                statement.setString(10, account.domain());
                statement.setString(11, account.normalizedAuthType());
                statement.setString(12, java.time.Instant.now().toString());
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }

    static void syncTagRules(Connection connection, EmailTagRulesConfig config) throws SQLException {
        execute(connection, "delete from tag_rules");
        execute(connection, "delete from tags");
        try (PreparedStatement tagStatement = connection.prepareStatement(
                "insert into tags (name, color) values (?, ?)");
                PreparedStatement ruleStatement = connection.prepareStatement(
                        "insert into tag_rules (tag_name, field_name, contains_value) values (?, ?, ?)")) {
            for (EmailTagRuleConfig rule : config.rules()) {
                if (rule.tag() == null || rule.tag().isBlank() || rule.contains() == null || rule.contains().isBlank()) {
                    continue;
                }
                tagStatement.setString(1, rule.tag().trim());
                tagStatement.setString(2, null);
                tagStatement.addBatch();
                ruleStatement.setString(1, rule.tag().trim());
                ruleStatement.setString(2, rule.normalizedField());
                ruleStatement.setString(3, rule.contains().trim());
                ruleStatement.addBatch();
            }
            tagStatement.executeBatch();
            ruleStatement.executeBatch();
        }
    }

    static void reapplyTags(Connection connection) throws SQLException {
        execute(connection, "delete from message_tags");
        try (PreparedStatement rules = connection.prepareStatement(
                "select tag_name, field_name, contains_value from tag_rules order by id");
                ResultSet resultSet = rules.executeQuery()) {
            while (resultSet.next()) {
                String tag = resultSet.getString(1);
                String field = resultSet.getString(2);
                String contains = resultSet.getString(3).toLowerCase(java.util.Locale.ROOT);
                String sqlField = switch (field) {
                case "recipient" -> "coalesce(to_summary, '')";
                case "subject" -> "coalesce(subject, '')";
                case "body" -> "coalesce(body_text, '')";
                default -> "coalesce(from_email, '')";
                };
                String sql = """
                        insert into message_tags (message_id, tag_name)
                        select m.id, ?
                        from messages m
                        where lower(%s) like ?
                          and not exists (
                              select 1
                              from message_tags existing
                              where existing.message_id = m.id
                                and existing.tag_name = ?
                          )""".formatted(sqlField);
                try (PreparedStatement insert = connection.prepareStatement(sql)) {
                    insert.setString(1, tag);
                    insert.setString(2, "%" + contains + "%");
                    insert.setString(3, tag);
                    insert.executeUpdate();
                }
            }
        }
    }

    static void upsertAccountMessages(Connection connection, String accountId, List<ImportedMailMessage> messages)
            throws SQLException {
        if (messages.isEmpty()) {
            return;
        }
        for (ImportedMailMessage message : messages) {
            if (message.internetMessageId() != null && !message.internetMessageId().isBlank()
                    && updateExistingMessage(connection, accountId, message) > 0) {
                continue;
            }
            insertMessage(connection, message);
        }
    }

    static void recordAccountSyncState(
            Connection connection,
            String accountId,
            String lastSyncAt,
            String statusMessage,
            boolean backfillComplete) throws SQLException {
        String normalizedStatus = statusMessage == null ? "" : statusMessage;
        try (PreparedStatement update = connection.prepareStatement("""
                update account_sync_state
                set last_sync_at = ?, status_message = ?, backfill_complete = ?
                where account_id = ?
                """)) {
            update.setString(1, lastSyncAt);
            update.setString(2, normalizedStatus);
            update.setInt(3, backfillComplete ? 1 : 0);
            update.setString(4, accountId);
            if (update.executeUpdate() > 0) {
                return;
            }
        }
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into account_sync_state (account_id, last_sync_at, status_message, backfill_complete)
                values (?, ?, ?, ?)
                """)) {
            insert.setString(1, accountId);
            insert.setString(2, lastSyncAt);
            insert.setString(3, normalizedStatus);
            insert.setInt(4, backfillComplete ? 1 : 0);
            insert.executeUpdate();
        }
    }

    static void appendSentDraft(
            Connection connection,
            String accountId,
            String accountName,
            String fromEmail,
            MailDraft draft,
            String sentAt) throws SQLException {
        ImportedMailMessage message = new ImportedMailMessage(
                accountId,
                "Sent",
                "<swim-local-" + System.nanoTime() + "@swim>",
                "sent:" + normalizeSubject(draft.subject()) + "|" + normalizeWhitespace(fromEmail) + "|"
                        + normalizeWhitespace(draft.to()),
                draft.subject(),
                accountName,
                fromEmail,
                draft.to(),
                sentAt,
                sentAt,
                snippet(draft.body()),
                draft.body(),
                false);
        upsertAccountMessages(connection, accountId, List.of(message));
        rebuildThreads(connection, accountId);
    }

    static MailSnapshot loadSnapshot(Connection connection, EmailPaths paths, int threadLimit) throws SQLException {
        List<MailAccountSummary> accounts = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select a.id, a.name, a.protocol,
                    coalesce((select count(*) from threads t where t.account_id = a.id), 0),
                    coalesce((select sum(t.unread_count) from threads t where t.account_id = a.id), 0),
                    s.last_sync_at,
                    s.status_message
                from accounts a
                left join account_sync_state s on s.account_id = a.id
                order by a.name
                """);
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                accounts.add(new MailAccountSummary(
                        resultSet.getString(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getInt(4),
                        resultSet.getInt(5),
                        resultSet.getString(6),
                        resultSet.getString(7)));
            }
        }

        List<MailThreadSummary> threads = loadThreadPage(connection, "", 0, threadLimit).threads();

        String status = statusMessage(accounts, threads, paths);
        return new MailSnapshot(accounts, threads, status);
    }

    static MailThreadPage loadThreadPage(Connection connection, String query, int offset, int limit) throws SQLException {
        int safeOffset = Math.max(0, offset);
        int safeLimit = Math.max(0, limit);
        String normalizedQuery = normalizeSearchQuery(query);
        int totalCount = countThreads(connection, normalizedQuery);
        if (safeLimit == 0 || safeOffset >= totalCount) {
            return new MailThreadPage(List.of(), totalCount);
        }

        List<MailThreadSummary> threads = new ArrayList<>();
        StringBuilder sql = new StringBuilder("""
                select t.id, t.account_id, t.subject, t.participants, t.snippet, t.last_message_at, t.unread_count, t.message_count
                from threads t
                """);
        if (!normalizedQuery.isBlank()) {
            sql.append("where ").append(threadSearchPredicate("t")).append("\n");
        }
        sql.append("""
                order by coalesce(t.last_message_at, '') desc, t.id desc
                limit ? offset ?
                """);
        try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
            int index = 1;
            if (!normalizedQuery.isBlank()) {
                index = bindSearchParameters(statement, index, normalizedQuery);
            }
            statement.setInt(index++, safeLimit);
            statement.setInt(index, safeOffset);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    long threadId = resultSet.getLong(1);
                    threads.add(new MailThreadSummary(
                            threadId,
                            resultSet.getString(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getInt(7) > 0,
                            resultSet.getInt(8),
                            loadTagsForThread(connection, threadId)));
                }
            }
        }
        return new MailThreadPage(threads, totalCount);
    }

    static MailMessageDetail loadMessage(Connection connection, long threadId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, subject,
                    trim(coalesce(from_name, '') || case when from_email is null or from_email = '' then '' else ' <' || from_email || '>' end),
                    to_summary,
                    coalesce(sent_at, received_at),
                    body_text
                from messages
                where thread_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                limit 1
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MailMessageDetail(
                            resultSet.getLong(1),
                            resultSet.getLong(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            loadTagsForThread(connection, threadId));
                }
            }
        }
        try (PreparedStatement statement = connection.prepareStatement("""
                select subject, participants, snippet, last_message_at
                from threads
                where id = ?
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MailMessageDetail(
                            0L,
                            threadId,
                            resultSet.getString(1),
                            resultSet.getString(2),
                            "",
                            resultSet.getString(4),
                            resultSet.getString(3),
                            loadTagsForThread(connection, threadId));
                }
            }
        }
        return new MailMessageDetail(0L, threadId, "(no message)", "", "", "", "", List.of());
    }

    static MessageHydrationTarget loadMessageHydrationTarget(Connection connection, long threadId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, account_id, folder_name, internet_message_id
                from messages
                where thread_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                limit 1
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MessageHydrationTarget(
                            resultSet.getLong(1),
                            resultSet.getLong(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5));
                }
            }
        }
        return null;
    }

    static void updateMessageBody(Connection connection, long messageId, long threadId, String bodyText) throws SQLException {
        String snippet = snippet(bodyText);
        try (PreparedStatement updateMessage = connection.prepareStatement("""
                update messages
                set body_text = ?, snippet = ?
                where id = ?
                """);
                PreparedStatement updateThread = connection.prepareStatement("""
                        update threads
                        set snippet = ?
                        where id = ?
                        """)) {
            updateMessage.setString(1, bodyText);
            updateMessage.setString(2, snippet);
            updateMessage.setLong(3, messageId);
            updateMessage.executeUpdate();

            updateThread.setString(1, snippet);
            updateThread.setLong(2, threadId);
            updateThread.executeUpdate();
        }
    }

    static int countMessages(Connection connection, String accountId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select count(*)
                from messages
                where account_id = ?
                """)) {
            statement.setString(1, accountId);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next() ? resultSet.getInt(1) : 0;
            }
        }
    }

    private static List<String> loadTagsForThread(Connection connection, long threadId) throws SQLException {
        List<String> tags = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct mt.tag_name
                from message_tags mt
                join messages m on m.id = mt.message_id
                where m.thread_id = ?
                order by mt.tag_name
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    tags.add(resultSet.getString(1));
                }
            }
        }
        return tags;
    }

    static void rebuildThreads(Connection connection, String accountId) throws SQLException {
        List<StoredMessage> rows = new ArrayList<>();
        try (PreparedStatement select = connection.prepareStatement("""
                select id, account_id, thread_key, folder_name, subject, from_name, from_email, to_summary,
                    sent_at, received_at, snippet, is_read
                from messages
                where account_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                """)) {
            select.setString(1, accountId);
            try (ResultSet resultSet = select.executeQuery()) {
                while (resultSet.next()) {
                    rows.add(new StoredMessage(
                            resultSet.getLong(1),
                            resultSet.getString(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            resultSet.getString(8),
                            resultSet.getString(9),
                            resultSet.getString(10),
                            resultSet.getString(11),
                            resultSet.getInt(12) == 0));
                }
            }
        }

        try (PreparedStatement deleteThreads = connection.prepareStatement("delete from threads where account_id = ?")) {
            deleteThreads.setString(1, accountId);
            deleteThreads.executeUpdate();
        }

        Map<String, List<StoredMessage>> grouped = new LinkedHashMap<>();
        for (StoredMessage row : rows) {
            String key = row.threadKey() == null || row.threadKey().isBlank()
                    ? "message:" + row.id()
                    : row.threadKey();
            grouped.computeIfAbsent(key, ignored -> new ArrayList<>()).add(row);
        }

        try (PreparedStatement updateMessageThread = connection.prepareStatement("""
                update messages
                set thread_id = ?
                where id = ?
                """)) {
            for (List<StoredMessage> group : grouped.values()) {
                StoredMessage latest = group.getFirst();
                long threadId = insertStoredThread(connection, accountId, group, latest);
                for (StoredMessage message : group) {
                    updateMessageThread.setLong(1, threadId);
                    updateMessageThread.setLong(2, message.id());
                    updateMessageThread.addBatch();
                }
            }
            updateMessageThread.executeBatch();
        }
    }

    private static long insertThread(
            Connection connection,
            String accountId,
            List<ImportedMailMessage> group,
            ImportedMailMessage latest) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into threads (
                    account_id, folder_name, subject, participants, snippet, last_message_at, unread_count, message_count
                ) values (?, ?, ?, ?, ?, ?, ?, ?)
                """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, accountId);
            statement.setString(2, latest.folderName());
            statement.setString(3, latest.subject());
            statement.setString(4, latest.participants());
            statement.setString(5, latest.snippet());
            statement.setString(6, latest.effectiveTimestamp());
            statement.setInt(7, (int) group.stream().filter(ImportedMailMessage::unread).count());
            statement.setInt(8, group.size());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getLong(1);
                }
            }
        }
        throw new SQLException("Failed to create thread for account " + accountId);
    }

    private static long insertStoredThread(
            Connection connection,
            String accountId,
            List<StoredMessage> group,
            StoredMessage latest) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into threads (
                    account_id, folder_name, subject, participants, snippet, last_message_at, unread_count, message_count
                ) values (?, ?, ?, ?, ?, ?, ?, ?)
                """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, accountId);
            statement.setString(2, latest.folderName());
            statement.setString(3, latest.subject());
            statement.setString(4, latest.participants());
            statement.setString(5, latest.snippet());
            statement.setString(6, latest.effectiveTimestamp());
            statement.setInt(7, (int) group.stream().filter(StoredMessage::unread).count());
            statement.setInt(8, group.size());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getLong(1);
                }
            }
        }
        throw new SQLException("Failed to create thread for account " + accountId);
    }

    private static int updateExistingMessage(Connection connection, String accountId, ImportedMailMessage message)
            throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                update messages
                set thread_key = ?, folder_name = ?, subject = ?, from_name = ?, from_email = ?, to_summary = ?,
                    sent_at = ?, received_at = ?, snippet = ?, body_text = case when ? = '' then body_text else ? end,
                    is_read = ?
                where account_id = ? and internet_message_id = ?
                """)) {
            statement.setString(1, message.threadKey());
            statement.setString(2, message.folderName());
            statement.setString(3, message.subject());
            statement.setString(4, message.fromName());
            statement.setString(5, message.fromEmail());
            statement.setString(6, message.toSummary());
            statement.setString(7, message.sentAt());
            statement.setString(8, message.receivedAt());
            statement.setString(9, message.snippet());
            statement.setString(10, message.bodyText() == null ? "" : message.bodyText());
            statement.setString(11, message.bodyText());
            statement.setInt(12, message.unread() ? 0 : 1);
            statement.setString(13, accountId);
            statement.setString(14, message.internetMessageId());
            return statement.executeUpdate();
        }
    }

    private static void insertMessage(Connection connection, ImportedMailMessage message) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into messages (
                    account_id, thread_id, thread_key, internet_message_id, folder_name, subject, from_name, from_email,
                    to_summary, sent_at, received_at, snippet, body_text, is_read
                ) values (?, null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """)) {
            statement.setString(1, message.accountId());
            statement.setString(2, message.threadKey());
            statement.setString(3, message.internetMessageId());
            statement.setString(4, message.folderName());
            statement.setString(5, message.subject());
            statement.setString(6, message.fromName());
            statement.setString(7, message.fromEmail());
            statement.setString(8, message.toSummary());
            statement.setString(9, message.sentAt());
            statement.setString(10, message.receivedAt());
            statement.setString(11, message.snippet());
            statement.setString(12, message.bodyText());
            statement.setInt(13, message.unread() ? 0 : 1);
            statement.executeUpdate();
        }
    }

    private static String statusMessage(
            List<MailAccountSummary> accounts,
            List<MailThreadSummary> threads,
            EmailPaths paths) {
        List<String> statuses = accounts.stream()
                .map(MailAccountSummary::syncStatus)
                .filter(status -> status != null && !status.isBlank())
                .distinct()
                .toList();
        if (!statuses.isEmpty() && threads.isEmpty()) {
            return String.join("  |  ", statuses);
        }
        if (!threads.isEmpty()) {
            return "";
        }
        if (!accounts.isEmpty()) {
            return "No mail has been synced yet. Press r to refresh.";
        }
        return "Configure accounts in " + paths.accountsPath()
                + " and tag rules in " + paths.tagRulesPath()
                + ". Mail is stored in " + paths.databaseFilePath() + ".";
    }

    private static String snippet(String body) {
        if (body == null) {
            return "";
        }
        String normalized = normalizeWhitespace(body);
        return normalized.length() > 180 ? normalized.substring(0, 180) : normalized;
    }

    private static String normalizeSubject(String subject) {
        if (subject == null) {
            return "";
        }
        return subject.strip().toLowerCase(java.util.Locale.ROOT);
    }

    private static String normalizeWhitespace(String text) {
        return text == null ? "" : text.replaceAll("\\s+", " ").trim();
    }

    private static String normalizeSearchQuery(String query) {
        return query == null ? "" : query.toLowerCase(java.util.Locale.ROOT).trim();
    }

    private static int countThreads(Connection connection, String query) throws SQLException {
        StringBuilder sql = new StringBuilder("select count(*) from threads t\n");
        if (!query.isBlank()) {
            sql.append("where ").append(threadSearchPredicate("t"));
        }
        try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
            if (!query.isBlank()) {
                bindSearchParameters(statement, 1, query);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next() ? resultSet.getInt(1) : 0;
            }
        }
    }

    private static String threadSearchPredicate(String threadAlias) {
        return """
                (
                    lower(coalesce(%1$s.subject, '')) like ?
                    or lower(coalesce(%1$s.participants, '')) like ?
                    or lower(coalesce(%1$s.snippet, '')) like ?
                    or exists (
                        select 1
                        from messages m
                        where m.thread_id = %1$s.id
                          and (
                              lower(coalesce(m.subject, '')) like ?
                              or lower(coalesce(m.from_name, '')) like ?
                              or lower(coalesce(m.from_email, '')) like ?
                              or lower(coalesce(m.to_summary, '')) like ?
                              or lower(coalesce(m.snippet, '')) like ?
                              or lower(coalesce(m.body_text, '')) like ?
                          )
                    )
                    or exists (
                        select 1
                        from message_tags mt
                        join messages tm on tm.id = mt.message_id
                        where tm.thread_id = %1$s.id
                          and lower(coalesce(mt.tag_name, '')) like ?
                    )
                )
                """.formatted(threadAlias);
    }

    private static int bindSearchParameters(PreparedStatement statement, int index, String query) throws SQLException {
        String like = "%" + query + "%";
        for (int i = 0; i < 10; i++) {
            statement.setString(index++, like);
        }
        return index;
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.execute();
        }
    }
}
