package org.fisk.swim.plugins.email;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;

import org.h2.fulltext.FullText;
import org.fisk.swim.mail.MailAccountSummary;
import org.fisk.swim.mail.MailDraft;
import org.fisk.swim.mail.MailMessageDetail;
import org.fisk.swim.mail.MailMessageSummary;
import org.fisk.swim.mail.MailSnapshot;
import org.fisk.swim.mail.MailThreadFilter;
import org.fisk.swim.mail.MailThreadPage;
import org.fisk.swim.mail.MailThreadSummary;

final class MailDb {
    record MessageHydrationTarget(long messageId, long threadId, String accountId, String folderName, String internetMessageId) {
    }

    private record StoredTagRule(String tag, String field, String contains, String match) {
    }

    private record ThreadQueryFilter(String predicateSql, List<Object> params) {
        ThreadQueryFilter {
            predicateSql = predicateSql == null ? "" : predicateSql;
            params = params == null ? List.of() : List.copyOf(params);
        }

        static ThreadQueryFilter none() {
            return new ThreadQueryFilter("", List.of());
        }
    }

    record StoredMessage(
            long id,
            String accountId,
            long threadId,
            String internetMessageId,
            String threadKey,
            String folderName,
            String subject,
            String fromName,
            String fromEmail,
            String toSummary,
            String sentAt,
            String receivedAt,
            String snippet,
            boolean unread) {
        String effectiveTimestamp() {
            if (receivedAt != null && !receivedAt.isBlank()) {
                return receivedAt;
            }
            if (sentAt != null && !sentAt.isBlank()) {
                return sentAt;
            }
            return "";
        }

        String participants() {
            String from = fromName != null && !fromName.isBlank() ? fromName : fromEmail;
            if (from == null || from.isBlank()) {
                from = "(unknown)";
            }
            if (toSummary == null || toSummary.isBlank()) {
                return from;
            }
            return from + " -> " + toSummary;
        }
    }

    private MailDb() {
    }

    static void initialize(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists accounts (
                    id text primary key,
                    name text not null,
                    protocol text not null,
                    host text,
                    port integer,
                    username text,
                    password_env text,
                    folder text,
                    ews_url text,
                    domain text,
                    auth_type text,
                    updated_at text not null
                )
                """);
        execute(connection, """
                create table if not exists threads (
                    id bigint generated by default as identity primary key,
                    account_id text not null,
                    folder_name text,
                    subject text,
                    participants text,
                    snippet text,
                    last_message_at text,
                    unread_count integer not null default 0,
                    message_count integer not null default 0
                )
                """);
        execute(connection, """
                create table if not exists messages (
                    id bigint generated by default as identity primary key,
                    account_id text not null,
                    thread_id integer,
                    thread_key text,
                    internet_message_id text,
                    folder_name text,
                    subject text,
                    from_name text,
                    from_email text,
                    to_summary text,
                    sent_at text,
                    received_at text,
                    snippet text,
                    body_text text,
                    is_read integer not null default 0
                )
                """);
        execute(connection, """
                create table if not exists message_recipients (
                    message_id bigint not null,
                    recipient_type text not null,
                    recipient_name text,
                    recipient_email text not null,
                    recipient_email_lc text not null,
                    primary key (message_id, recipient_type, recipient_email_lc)
                )
                """);
        execute(connection, """
                create table if not exists tags (
                    name text primary key,
                    color text
                )
                """);
        execute(connection, """
                create table if not exists tag_rules (
                    id bigint generated by default as identity primary key,
                    tag_name text not null,
                    field_name text not null,
                    contains_value text not null
                )
                """);
        execute(connection, """
                create table if not exists message_tags (
                    message_id integer not null,
                    tag_name text not null,
                    primary key (message_id, tag_name)
                )
                """);
        execute(connection, """
                create table if not exists account_sync_state (
                    account_id text primary key,
                    last_sync_at text,
                    status_message text not null default '',
                    backfill_complete integer not null default 0,
                    last_seen_uid bigint not null default 0,
                    next_backfill_uid bigint not null default 0
                )
                """);
        execute(connection, "alter table messages add column if not exists thread_key text");
        execute(connection, "alter table tag_rules add column if not exists match_type text");
        execute(connection,
                "alter table account_sync_state add column if not exists backfill_complete integer not null default 0");
        execute(connection,
                "alter table account_sync_state add column if not exists last_seen_uid bigint not null default 0");
        execute(connection,
                "alter table account_sync_state add column if not exists next_backfill_uid bigint not null default 0");
        execute(connection,
                "create unique index if not exists idx_messages_account_message_id on messages (account_id, internet_message_id)");
        execute(connection, "create index if not exists idx_threads_account_id on threads (account_id)");
        execute(connection, "create index if not exists idx_threads_last_message_at on threads (last_message_at, id)");
        execute(connection, "create index if not exists idx_messages_thread_id on messages (thread_id)");
        execute(connection, "create index if not exists idx_messages_account_id on messages (account_id)");
        execute(connection, "create index if not exists idx_messages_is_read on messages (is_read)");
        execute(connection, "create index if not exists idx_messages_is_read_thread_id on messages (is_read, thread_id)");
        execute(connection, "create index if not exists idx_messages_thread_received_at on messages (thread_id, received_at, id)");
        execute(connection, "create index if not exists idx_messages_from_email on messages (from_email)");
        execute(connection, "create index if not exists idx_messages_to_summary on messages (to_summary)");
        execute(connection, "create index if not exists idx_messages_subject on messages (subject)");
        execute(connection, "create index if not exists idx_message_recipients_message_id on message_recipients (message_id)");
        execute(connection, "create index if not exists idx_message_recipients_email_lc on message_recipients (recipient_email_lc)");
        execute(connection, "create index if not exists idx_message_recipients_type_email on message_recipients (recipient_type, recipient_email_lc)");
        execute(connection, "create index if not exists idx_message_recipients_email_message on message_recipients (recipient_email_lc, message_id)");
        execute(connection, "create index if not exists idx_message_tags_message_id on message_tags (message_id)");
        ensureFullTextIndex(connection);
    }

    static void syncAccounts(Connection connection, EmailAccountsConfig config) throws SQLException {
        execute(connection, "delete from accounts");
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into accounts (
                    id, name, protocol, host, port, username, password_env, folder, ews_url, domain, auth_type, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """)) {
            for (EmailAccountConfig account : config.accounts()) {
                statement.setString(1, account.normalizedId());
                statement.setString(2, account.displayName());
                statement.setString(3, account.normalizedProtocol());
                statement.setString(4, account.host());
                if (account.port() == null) {
                    statement.setNull(5, java.sql.Types.INTEGER);
                } else {
                    statement.setInt(5, account.port());
                }
                statement.setString(6, account.username());
                statement.setString(7, account.passwordEnv());
                statement.setString(8, account.folder());
                statement.setString(9, account.ewsUrl());
                statement.setString(10, account.domain());
                statement.setString(11, account.normalizedAuthType());
                statement.setString(12, java.time.Instant.now().toString());
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }

    static void syncTagRules(Connection connection, EmailTagRulesConfig config) throws SQLException {
        execute(connection, "delete from tag_rules");
        try (PreparedStatement ruleStatement = connection.prepareStatement(
                        "insert into tag_rules (tag_name, field_name, contains_value, match_type) values (?, ?, ?, ?)")) {
            for (EmailTagRuleConfig rule : config.rules()) {
                if (rule.tag() == null || rule.tag().isBlank() || rule.contains() == null || rule.contains().isBlank()) {
                    continue;
                }
                ruleStatement.setString(1, rule.tag().trim());
                ruleStatement.setString(2, rule.normalizedField());
                ruleStatement.setString(3, rule.contains().trim());
                ruleStatement.setString(4, rule.normalizedMatch());
                ruleStatement.addBatch();
            }
            ruleStatement.executeBatch();
        }
    }

    static void reapplyTags(Connection connection) throws SQLException {
        // Tags are resolved dynamically from tag_rules and message/thread fields.
    }

    static void upsertAccountMessages(Connection connection, String accountId, List<ImportedMailMessage> messages)
            throws SQLException {
        if (messages.isEmpty()) {
            return;
        }
        for (ImportedMailMessage message : messages) {
            Long existingMessageId = message.internetMessageId() != null && !message.internetMessageId().isBlank()
                    ? updateExistingMessage(connection, accountId, message)
                    : null;
            if (existingMessageId != null) {
                replaceMessageRecipients(connection, existingMessageId, message.recipients());
                continue;
            }
            insertMessage(connection, message);
        }
    }

    static void recordAccountSyncState(
            Connection connection,
            String accountId,
            String lastSyncAt,
            String statusMessage,
            boolean backfillComplete,
            long lastSeenUid,
            long nextBackfillUid) throws SQLException {
        String normalizedStatus = statusMessage == null ? "" : statusMessage;
        try (PreparedStatement update = connection.prepareStatement("""
                update account_sync_state
                set last_sync_at = ?, status_message = ?, backfill_complete = ?, last_seen_uid = ?, next_backfill_uid = ?
                where account_id = ?
                """)) {
            update.setString(1, lastSyncAt);
            update.setString(2, normalizedStatus);
            update.setInt(3, backfillComplete ? 1 : 0);
            update.setLong(4, Math.max(0L, lastSeenUid));
            update.setLong(5, Math.max(0L, nextBackfillUid));
            update.setString(6, accountId);
            if (update.executeUpdate() > 0) {
                return;
            }
        }
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into account_sync_state (
                    account_id, last_sync_at, status_message, backfill_complete, last_seen_uid, next_backfill_uid
                ) values (?, ?, ?, ?, ?, ?)
                """)) {
            insert.setString(1, accountId);
            insert.setString(2, lastSyncAt);
            insert.setString(3, normalizedStatus);
            insert.setInt(4, backfillComplete ? 1 : 0);
            insert.setLong(5, Math.max(0L, lastSeenUid));
            insert.setLong(6, Math.max(0L, nextBackfillUid));
            insert.executeUpdate();
        }
    }

    static java.util.Map<String, AccountSyncState> loadAccountSyncStates(Connection connection) throws SQLException {
        var states = new java.util.LinkedHashMap<String, AccountSyncState>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select account_id, last_sync_at, backfill_complete, last_seen_uid, next_backfill_uid
                from account_sync_state
                """);
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                states.put(resultSet.getString(1), new AccountSyncState(
                        resultSet.getString(1),
                        resultSet.getString(2),
                        resultSet.getInt(3) != 0,
                        resultSet.getLong(4),
                        resultSet.getLong(5)));
            }
        }
        return states;
    }

    static void appendSentDraft(
            Connection connection,
            String accountId,
            String accountName,
            String fromEmail,
            MailDraft draft,
            String sentAt) throws SQLException {
        ImportedMailMessage message = new ImportedMailMessage(
                accountId,
                "Sent",
                "<swim-local-" + System.nanoTime() + "@swim>",
                "sent:" + normalizeSubject(draft.subject()) + "|" + normalizeWhitespace(fromEmail) + "|"
                        + normalizeWhitespace(recipientSummary(draft)),
                draft.subject(),
                accountName,
                fromEmail,
                recipientSummary(draft),
                recipients(draft),
                sentAt,
                sentAt,
                snippet(draft.body()),
                draft.body(),
                false);
        upsertAccountMessages(connection, accountId, List.of(message));
        rebuildThreads(connection, accountId);
    }

    static MailSnapshot loadSnapshot(Connection connection, EmailPaths paths, int threadLimit) throws SQLException {
        List<MailAccountSummary> accounts = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select a.id, a.name, a.protocol,
                    coalesce((select count(*) from threads t where t.account_id = a.id), 0),
                    coalesce((select sum(t.unread_count) from threads t where t.account_id = a.id), 0),
                    s.last_sync_at,
                    s.status_message
                from accounts a
                left join account_sync_state s on s.account_id = a.id
                order by a.name
                """);
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                accounts.add(new MailAccountSummary(
                        resultSet.getString(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getInt(4),
                        resultSet.getInt(5),
                        resultSet.getString(6),
                        resultSet.getString(7)));
            }
        }

        List<MailThreadSummary> threads = loadThreadPage(connection, "", 0, threadLimit, MailThreadFilter.all()).threads();

        String status = statusMessage(accounts, threads, paths);
        return new MailSnapshot(accounts, threads, status);
    }

    static MailThreadPage loadThreadPage(Connection connection, String query, int offset, int limit) throws SQLException {
        return loadThreadPage(connection, query, offset, limit, MailThreadFilter.all());
    }

    static MailThreadPage loadThreadPage(
            Connection connection,
            String query,
            int offset,
            int limit,
            MailThreadFilter filter) throws SQLException {
        int safeOffset = Math.max(0, offset);
        int safeLimit = Math.max(0, limit);
        String normalizedQuery = normalizeSearchQuery(query);
        boolean includeTagMatch = hasMatchingTagName(connection, normalizedQuery);
        MailThreadFilter effectiveFilter = filter == null ? MailThreadFilter.all() : filter;
        ThreadQueryFilter queryFilter = threadQueryFilter(connection, effectiveFilter);
        int totalCount = countThreads(connection, normalizedQuery, includeTagMatch, queryFilter);
        if (safeLimit == 0 || safeOffset >= totalCount) {
            return new MailThreadPage(List.of(), totalCount);
        }

        List<MailThreadSummary> threads = new ArrayList<>();
        StringBuilder sql = new StringBuilder("""
                select t.id, t.account_id, t.subject, t.participants, t.snippet, t.last_message_at, t.unread_count, t.message_count,
                    %s
                from threads t
                join accounts a on a.id = t.account_id
                """.formatted(threadAddressedToAccountSql("t", "a")));
        String whereClause = threadWhereClause("t", "a", normalizedQuery, includeTagMatch, queryFilter);
        if (!whereClause.isBlank()) {
            sql.append("where ").append(whereClause).append("\n");
        }
        sql.append("""
                order by coalesce(t.last_message_at, '') desc, t.id desc
                limit ? offset ?
                """);
        try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
            int index = bindThreadParameters(statement, 1, normalizedQuery, includeTagMatch, queryFilter);
            statement.setInt(index++, safeLimit);
            statement.setInt(index, safeOffset);
            try (ResultSet resultSet = statement.executeQuery()) {
                var threadIds = new ArrayList<Long>();
                while (resultSet.next()) {
                    long threadId = resultSet.getLong(1);
                    threadIds.add(threadId);
                    threads.add(new MailThreadSummary(
                            threadId,
                            resultSet.getString(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getInt(7) > 0,
                            resultSet.getInt(8),
                            List.of(),
                            resultSet.getInt(9) != 0));
                }
                if (!threads.isEmpty()) {
                    Map<Long, List<String>> tagsByThreadId = loadTagsForThreads(connection, threadIds);
                    for (int i = 0; i < threads.size(); i++) {
                        MailThreadSummary thread = threads.get(i);
                        threads.set(i, new MailThreadSummary(
                                thread.threadId(),
                                thread.accountId(),
                                thread.subject(),
                                thread.participants(),
                                thread.snippet(),
                                thread.receivedAt(),
                                thread.unread(),
                                thread.messageCount(),
                                tagsByThreadId.getOrDefault(thread.threadId(), List.of()),
                                thread.addressedToAccount()));
                    }
                }
            }
        }
        return new MailThreadPage(threads, totalCount);
    }

    static MailMessageDetail loadMessage(Connection connection, long threadId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, subject,
                    trim(coalesce(from_name, '') || case when from_email is null or from_email = '' then '' else ' <' || from_email || '>' end),
                    to_summary,
                    coalesce(sent_at, received_at),
                    body_text
                from messages
                where thread_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                limit 1
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    long messageId = resultSet.getLong(1);
                    return new MailMessageDetail(
                            messageId,
                            resultSet.getLong(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            recipientSummary(connection, messageId, "CC"),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            loadTagsForThread(connection, threadId));
                }
            }
        }
        try (PreparedStatement statement = connection.prepareStatement("""
                select subject, participants, snippet, last_message_at
                from threads
                where id = ?
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MailMessageDetail(
                            0L,
                            threadId,
                            resultSet.getString(1),
                            resultSet.getString(2),
                            "",
                            "",
                            resultSet.getString(4),
                            resultSet.getString(3),
                            loadTagsForThread(connection, threadId));
                }
            }
        }
        return new MailMessageDetail(0L, threadId, "(no message)", "", "", "", "", "", List.of());
    }

    static MailMessageDetail loadMessageById(Connection connection, long messageId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, subject,
                    trim(coalesce(from_name, '') || case when from_email is null or from_email = '' then '' else ' <' || from_email || '>' end),
                    to_summary,
                    coalesce(sent_at, received_at),
                    body_text
                from messages
                where id = ?
                """)) {
            statement.setLong(1, messageId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    long threadId = resultSet.getLong(2);
                    return new MailMessageDetail(
                            resultSet.getLong(1),
                            threadId,
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            recipientSummary(connection, messageId, "CC"),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            loadTagsForThread(connection, threadId));
                }
            }
        }
        return new MailMessageDetail(0L, 0L, "(no message)", "", "", "", "", "", List.of());
    }

    private static String recipientSummary(Connection connection, long messageId, String type) throws SQLException {
        var values = new ArrayList<String>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select recipient_name, recipient_email
                from message_recipients
                where message_id = ? and recipient_type = ?
                order by recipient_email_lc
                """)) {
            statement.setLong(1, messageId);
            statement.setString(2, type);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    String name = resultSet.getString(1);
                    String email = resultSet.getString(2);
                    values.add(name != null && !name.isBlank() ? name : email);
                }
            }
        }
        return String.join(", ", values);
    }

    static MessageHydrationTarget loadMessageHydrationTarget(Connection connection, long threadId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, account_id, folder_name, internet_message_id
                from messages
                where thread_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                limit 1
                """)) {
            statement.setLong(1, threadId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MessageHydrationTarget(
                            resultSet.getLong(1),
                            resultSet.getLong(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5));
                }
            }
        }
        return null;
    }

    static MessageHydrationTarget loadMessageHydrationTargetByMessageId(Connection connection, long messageId)
            throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, thread_id, account_id, folder_name, internet_message_id
                from messages
                where id = ?
                """)) {
            statement.setLong(1, messageId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new MessageHydrationTarget(
                            resultSet.getLong(1),
                            resultSet.getLong(2),
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5));
                }
            }
        }
        return null;
    }

    static void updateMessageBody(Connection connection, long messageId, long threadId, String bodyText) throws SQLException {
        String snippet = snippet(bodyText);
        try (PreparedStatement updateMessage = connection.prepareStatement("""
                update messages
                set body_text = ?, snippet = ?
                where id = ?
                """);
                PreparedStatement updateThread = connection.prepareStatement("""
                        update threads
                        set snippet = ?
                        where id = ?
                        """)) {
            updateMessage.setString(1, bodyText);
            updateMessage.setString(2, snippet);
            updateMessage.setLong(3, messageId);
            updateMessage.executeUpdate();

            updateThread.setString(1, snippet);
            updateThread.setLong(2, threadId);
            updateThread.executeUpdate();
        }
    }

    static int countMessages(Connection connection, String accountId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select count(*)
                from messages
                where account_id = ?
                """)) {
            statement.setString(1, accountId);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next() ? resultSet.getInt(1) : 0;
            }
        }
    }

    static List<String> loadTagNames(Connection connection) throws SQLException {
        var tags = new ArrayList<String>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select tag_name
                from (
                    select tag_name, min(id) as first_rule_id
                    from tag_rules
                    group by tag_name
                )
                order by first_rule_id
                """);
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                tags.add(resultSet.getString(1));
            }
        }
        return List.copyOf(tags);
    }

    static Map<String, Integer> loadTagUnreadCounts(Connection connection) throws SQLException {
        List<StoredTagRule> rules = loadTagRules(connection);
        var counts = aggregateNonTokenTagUnreadCounts(connection);
        for (StoredTagRule rule : rules) {
            if ("token".equals(rule.match())) {
                counts.put(rule.tag(), matchingMessageIdsForRule(connection, rule, true).size());
            } else {
                counts.putIfAbsent(rule.tag(), 0);
            }
        }
        return counts;
    }

    static int loadUnsortedUnreadCount(Connection connection) throws SQLException {
        List<StoredTagRule> rules = loadTagRules(connection);
        boolean hasTokenRules = rules.stream().anyMatch(rule -> "token".equals(rule.match()));
        if (!hasTokenRules) {
            try (PreparedStatement statement = connection.prepareStatement("""
                    select count(*)
                    from messages m
                    where m.is_read = 0
                      and (
                          %s
                          or not exists (
                              select 1
                              from tag_rules tr
                              where coalesce(tr.match_type, 'contains') <> 'token'
                                and %s
                          )
                      )
                    """.formatted(messageAddressedToAccountSql("m"), nonTokenRuleMatchesMessageSql("m")));
                    ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1);
            }
        }

        var unread = new LinkedHashSet<Long>();
        var addressedToAccount = directlyAddressedUnreadMessageIds(connection);
        try (PreparedStatement statement = connection.prepareStatement("""
                select id
                from messages m
                where m.is_read = 0
                  and (
                      %s
                      or not exists (
                          select 1
                          from tag_rules tr
                          where coalesce(tr.match_type, 'contains') <> 'token'
                            and %s
                      )
                  )
                """.formatted(messageAddressedToAccountSql("m"), nonTokenRuleMatchesMessageSql("m")));
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                unread.add(resultSet.getLong(1));
            }
        }
        for (StoredTagRule rule : rules) {
            if ("token".equals(rule.match())) {
                for (Long messageId : matchingMessageIdsForRule(connection, rule, true)) {
                    if (!addressedToAccount.contains(messageId)) {
                        unread.remove(messageId);
                    }
                }
            }
        }
        return unread.size();
    }

    static void markMessageRead(Connection connection, long messageId) throws SQLException {
        Long threadId = null;
        try (PreparedStatement update = connection.prepareStatement("""
                update messages
                set is_read = 1
                where id = ? and is_read = 0
                """)) {
            update.setLong(1, messageId);
            if (update.executeUpdate() == 0) {
                return;
            }
        }
        try (PreparedStatement query = connection.prepareStatement("""
                select thread_id
                from messages
                where id = ?
                """)) {
            query.setLong(1, messageId);
            try (ResultSet resultSet = query.executeQuery()) {
                if (resultSet.next()) {
                    threadId = resultSet.getLong(1);
                }
            }
        }
        if (threadId == null) {
            return;
        }
        try (PreparedStatement updateThread = connection.prepareStatement("""
                update threads
                set unread_count = (
                    select count(*)
                    from messages
                    where thread_id = ? and is_read = 0
                )
                where id = ?
                """)) {
            updateThread.setLong(1, threadId);
            updateThread.setLong(2, threadId);
            updateThread.executeUpdate();
        }
    }

    private static List<String> loadTagsForThread(Connection connection, long threadId) throws SQLException {
        return loadTagsForThreads(connection, List.of(threadId)).getOrDefault(threadId, List.of());
    }

    private static Map<Long, List<String>> loadTagsForThreads(Connection connection, List<Long> threadIds) throws SQLException {
        var result = new LinkedHashMap<Long, List<String>>();
        if (threadIds == null || threadIds.isEmpty()) {
            return result;
        }
        var orderedThreadIds = threadIds.stream()
                .filter(java.util.Objects::nonNull)
                .distinct()
                .toList();
        if (orderedThreadIds.isEmpty()) {
            return result;
        }
        for (Long threadId : orderedThreadIds) {
            result.put(threadId, new ArrayList<>());
        }
        for (StoredTagRule rule : loadTagRules(connection)) {
            for (Long threadId : matchingThreadIdsForRule(connection, orderedThreadIds, rule)) {
                List<String> values = result.get(threadId);
                if (values != null && !values.contains(rule.tag())) {
                    values.add(rule.tag());
                }
            }
        }
        var normalized = new LinkedHashMap<Long, List<String>>();
        for (Map.Entry<Long, List<String>> entry : result.entrySet()) {
            normalized.put(entry.getKey(), List.copyOf(entry.getValue()));
        }
        return normalized;
    }

    private static List<StoredTagRule> loadTagRules(Connection connection) throws SQLException {
        var rules = new ArrayList<StoredTagRule>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select tag_name, field_name, contains_value, coalesce(match_type, 'contains')
                from tag_rules
                order by id
                """);
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                rules.add(new StoredTagRule(
                        resultSet.getString(1),
                        normalizeField(resultSet.getString(2)),
                        resultSet.getString(3),
                        normalizeMatch(resultSet.getString(4))));
            }
        }
        return List.copyOf(rules);
    }

    private static List<StoredTagRule> loadTagRules(Connection connection, String tagName) throws SQLException {
        if (tagName == null || tagName.isBlank()) {
            return List.of();
        }
        var rules = new ArrayList<StoredTagRule>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select tag_name, field_name, contains_value, coalesce(match_type, 'contains')
                from tag_rules
                where tag_name = ?
                order by id
                """)) {
            statement.setString(1, tagName);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    rules.add(new StoredTagRule(
                            resultSet.getString(1),
                            normalizeField(resultSet.getString(2)),
                            resultSet.getString(3),
                            normalizeMatch(resultSet.getString(4))));
                }
            }
        }
        return List.copyOf(rules);
    }

    private static Map<String, Integer> aggregateNonTokenTagUnreadCounts(Connection connection) throws SQLException {
        var counts = new LinkedHashMap<String, Integer>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select tr.tag_name, count(distinct m.id)
                from tag_rules tr
                join messages m on m.is_read = 0
                where coalesce(tr.match_type, 'contains') <> 'token'
                  and %s
                group by tr.tag_name
                order by tr.tag_name
                """.formatted(nonTokenRuleMatchesMessageSql("m")));
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                counts.put(resultSet.getString(1), resultSet.getInt(2));
            }
        }
        return counts;
    }

    private static List<Long> directlyAddressedUnreadMessageIds(Connection connection) throws SQLException {
        var ids = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select m.id
                from messages m
                where m.is_read = 0
                  and %s
                """.formatted(messageAddressedToAccountSql("m")));
                ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                ids.add(resultSet.getLong(1));
            }
        }
        return List.copyOf(ids);
    }

    private static String messageAddressedToAccountSql(String messageAlias) {
        return """
                exists (
                    select 1
                    from message_recipients mr
                    join accounts a on a.id = %1$s.account_id
                    where mr.message_id = %1$s.id
                      and mr.recipient_type in ('TO', 'CC')
                      and lower(coalesce(a.username, '')) <> ''
                      and mr.recipient_email_lc = lower(a.username)
                )
                """.formatted(messageAlias);
    }

    private static String threadAddressedToAccountSql(String threadAlias, String accountAlias) {
        return """
                exists (
                    select 1
                    from messages m
                    join message_recipients mr on mr.message_id = m.id
                    where m.thread_id = %1$s.id
                      and mr.recipient_type in ('TO', 'CC')
                      and lower(coalesce(%2$s.username, '')) <> ''
                      and mr.recipient_email_lc = lower(%2$s.username)
                )
                """.formatted(threadAlias, accountAlias);
    }

    private static String nonTokenRuleMatchesMessageSql(String messageAlias) {
        return """
                (
                    (coalesce(tr.field_name, 'sender') = 'sender'
                        and (
                            (coalesce(tr.match_type, 'contains') = 'exact' and lower(coalesce(%1$s.from_email, '')) = lower(tr.contains_value))
                            or (coalesce(tr.match_type, 'contains') = 'prefix' and lower(coalesce(%1$s.from_email, '')) like lower(tr.contains_value) || '%%')
                            or (coalesce(tr.match_type, 'contains') = 'contains' and lower(coalesce(%1$s.from_email, '')) like '%%' || lower(tr.contains_value) || '%%')
                        ))
                    or (tr.field_name = 'subject'
                        and (
                            (coalesce(tr.match_type, 'contains') = 'exact' and lower(coalesce(%1$s.subject, '')) = lower(tr.contains_value))
                            or (coalesce(tr.match_type, 'contains') = 'prefix' and lower(coalesce(%1$s.subject, '')) like lower(tr.contains_value) || '%%')
                            or (coalesce(tr.match_type, 'contains') = 'contains' and lower(coalesce(%1$s.subject, '')) like '%%' || lower(tr.contains_value) || '%%')
                        ))
                    or (tr.field_name = 'body'
                        and (
                            (coalesce(tr.match_type, 'contains') = 'exact' and lower(coalesce(%1$s.body_text, '')) = lower(tr.contains_value))
                            or (coalesce(tr.match_type, 'contains') = 'prefix' and lower(coalesce(%1$s.body_text, '')) like lower(tr.contains_value) || '%%')
                            or (coalesce(tr.match_type, 'contains') = 'contains' and lower(coalesce(%1$s.body_text, '')) like '%%' || lower(tr.contains_value) || '%%')
                        ))
                    or (tr.field_name = 'recipient'
                        and exists (
                            select 1
                            from message_recipients mr
                            where mr.message_id = %1$s.id
                              and (
                                  (coalesce(tr.match_type, 'contains') = 'exact' and mr.recipient_email_lc = lower(tr.contains_value))
                                  or (coalesce(tr.match_type, 'contains') = 'prefix' and mr.recipient_email_lc like lower(tr.contains_value) || '%%')
                                  or (coalesce(tr.match_type, 'contains') = 'contains' and mr.recipient_email_lc like '%%' || lower(tr.contains_value) || '%%')
                              )
                        ))
                )
                """.formatted(messageAlias);
    }

    private static List<Long> matchingMessageIdsForRule(
            Connection connection,
            StoredTagRule rule,
            boolean unreadOnly) throws SQLException {
        return switch (rule.match()) {
        case "exact" -> matchingMessageIdsForColumnRule(connection, rule, "=", unreadOnly);
        case "prefix" -> matchingMessageIdsForColumnRule(connection, rule, "prefix", unreadOnly);
        case "token" -> matchingMessageIdsForTokenRule(connection, rule, unreadOnly);
        default -> matchingMessageIdsForColumnRule(connection, rule, "contains", unreadOnly);
        };
    }

    private static List<Long> matchingMessageIdsForColumnRule(
            Connection connection,
            StoredTagRule rule,
            String mode,
            boolean unreadOnly) throws SQLException {
        if ("recipient".equals(rule.field())) {
            return matchingMessageIdsForRecipientRule(connection, rule, mode, unreadOnly);
        }
        String column = switch (rule.field()) {
        case "subject" -> "subject";
        case "body" -> "body_text";
        default -> "from_email";
        };
        String predicate = switch (mode) {
        case "=" -> "lower(coalesce(" + column + ", '')) = ?";
        case "prefix" -> "lower(coalesce(" + column + ", '')) like ?";
        default -> "lower(coalesce(" + column + ", '')) like ?";
        };
        var matched = new ArrayList<Long>();
        String unreadClause = unreadOnly ? "and is_read = 0" : "";
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct id
                from messages
                where %s
                  %s
                order by id
                """.formatted(predicate, unreadClause))) {
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(1, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingMessageIdsForRecipientRule(
            Connection connection,
            StoredTagRule rule,
            String mode,
            boolean unreadOnly) throws SQLException {
        String predicate = switch (mode) {
        case "=" -> "mr.recipient_email_lc = ?";
        case "prefix" -> "mr.recipient_email_lc like ?";
        default -> "mr.recipient_email_lc like ?";
        };
        var matched = new ArrayList<Long>();
        String unreadClause = unreadOnly ? "and m.is_read = 0" : "";
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct m.id
                from messages m
                join message_recipients mr on mr.message_id = m.id
                where %s
                  %s
                order by m.id
                """.formatted(predicate, unreadClause))) {
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(1, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForRule(
            Connection connection,
            StoredTagRule rule) throws SQLException {
        return switch (rule.match()) {
        case "exact" -> matchingThreadIdsForColumnRule(connection, rule, "=");
        case "prefix" -> matchingThreadIdsForColumnRule(connection, rule, "prefix");
        case "token" -> matchingThreadIdsForTokenRule(connection, rule);
        default -> matchingThreadIdsForColumnRule(connection, rule, "contains");
        };
    }

    private static List<Long> matchingThreadIdsForRule(
            Connection connection,
            List<Long> threadIds,
            StoredTagRule rule) throws SQLException {
        return switch (rule.match()) {
        case "exact" -> matchingThreadIdsForColumnRule(connection, threadIds, rule, "=");
        case "prefix" -> matchingThreadIdsForColumnRule(connection, threadIds, rule, "prefix");
        case "token" -> matchingThreadIdsForTokenRule(connection, threadIds, rule);
        default -> matchingThreadIdsForColumnRule(connection, threadIds, rule, "contains");
        };
    }

    private static List<Long> matchingThreadIdsForColumnRule(
            Connection connection,
            StoredTagRule rule,
            String mode) throws SQLException {
        if ("recipient".equals(rule.field())) {
            return matchingThreadIdsForRecipientRule(connection, rule, mode);
        }
        String column = switch (rule.field()) {
        case "subject" -> "subject";
        case "body" -> "body_text";
        default -> "from_email";
        };
        String predicate = switch (mode) {
        case "=" -> "lower(coalesce(" + column + ", '')) = ?";
        case "prefix" -> "lower(coalesce(" + column + ", '')) like ?";
        default -> "lower(coalesce(" + column + ", '')) like ?";
        };
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct thread_id
                from messages
                where %s
                order by thread_id
                """.formatted(predicate))) {
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(1, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForColumnRule(
            Connection connection,
            List<Long> threadIds,
            StoredTagRule rule,
            String mode) throws SQLException {
        if ("recipient".equals(rule.field())) {
            return matchingThreadIdsForRecipientRule(connection, threadIds, rule, mode);
        }
        String column = switch (rule.field()) {
        case "subject" -> "subject";
        case "body" -> "body_text";
        default -> "from_email";
        };
        String placeholders = String.join(", ", java.util.Collections.nCopies(threadIds.size(), "?"));
        String predicate = switch (mode) {
        case "=" -> "lower(coalesce(" + column + ", '')) = ?";
        case "prefix" -> "lower(coalesce(" + column + ", '')) like ?";
        default -> "lower(coalesce(" + column + ", '')) like ?";
        };
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct thread_id
                from messages
                where thread_id in (%s)
                  and %s
                order by thread_id
                """.formatted(placeholders, predicate))) {
            int index = 1;
            for (Long threadId : threadIds) {
                statement.setLong(index++, threadId);
            }
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(index, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForRecipientRule(
            Connection connection,
            StoredTagRule rule,
            String mode) throws SQLException {
        String predicate = switch (mode) {
        case "=" -> "mr.recipient_email_lc = ?";
        case "prefix" -> "mr.recipient_email_lc like ?";
        default -> "mr.recipient_email_lc like ?";
        };
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct m.thread_id
                from messages m
                join message_recipients mr on mr.message_id = m.id
                where %s
                order by m.thread_id
                """.formatted(predicate))) {
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(1, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForRecipientRule(
            Connection connection,
            List<Long> threadIds,
            StoredTagRule rule,
            String mode) throws SQLException {
        String placeholders = String.join(", ", java.util.Collections.nCopies(threadIds.size(), "?"));
        String predicate = switch (mode) {
        case "=" -> "mr.recipient_email_lc = ?";
        case "prefix" -> "mr.recipient_email_lc like ?";
        default -> "mr.recipient_email_lc like ?";
        };
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct m.thread_id
                from messages m
                join message_recipients mr on mr.message_id = m.id
                where m.thread_id in (%s)
                  and %s
                order by m.thread_id
                """.formatted(placeholders, predicate))) {
            int index = 1;
            for (Long threadId : threadIds) {
                statement.setLong(index++, threadId);
            }
            String normalized = rule.contains().toLowerCase(java.util.Locale.ROOT);
            statement.setString(index, switch (mode) {
            case "=" -> normalized;
            case "prefix" -> normalized + "%";
            default -> "%" + normalized + "%";
            });
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForTokenRule(
            Connection connection,
            StoredTagRule rule) throws SQLException {
        if (!"subject".equals(rule.field()) && !"body".equals(rule.field())) {
            return matchingThreadIdsForColumnRule(connection, rule, "contains");
        }
        var messageIds = new ArrayList<Long>();
        try (ResultSet resultSet = FullText.searchData(connection, rule.contains(), 0, 0)) {
            while (resultSet.next()) {
                if (!"MESSAGES".equalsIgnoreCase(resultSet.getString("TABLE"))) {
                    continue;
                }
                Object[] columns = (Object[]) resultSet.getObject("COLUMNS");
                Object[] keys = (Object[]) resultSet.getObject("KEYS");
                if (columns == null || keys == null) {
                    continue;
                }
                for (int i = 0; i < columns.length && i < keys.length; i++) {
                    if ("ID".equalsIgnoreCase(String.valueOf(columns[i]))) {
                        messageIds.add(Long.parseLong(String.valueOf(keys[i])));
                    }
                }
            }
        }
        if (messageIds.isEmpty()) {
            return List.of();
        }
        String messagePlaceholders = String.join(", ", java.util.Collections.nCopies(messageIds.size(), "?"));
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct thread_id
                from messages
                where id in (%s)
                order by thread_id
                """.formatted(messagePlaceholders))) {
            int index = 1;
            for (Long messageId : messageIds) {
                statement.setLong(index++, messageId);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingThreadIdsForTokenRule(
            Connection connection,
            List<Long> threadIds,
            StoredTagRule rule) throws SQLException {
        if (!"subject".equals(rule.field()) && !"body".equals(rule.field())) {
            return matchingThreadIdsForColumnRule(connection, threadIds, rule, "contains");
        }
        var messageIds = new ArrayList<Long>();
        try (ResultSet resultSet = FullText.searchData(connection, rule.contains(), 0, 0)) {
            while (resultSet.next()) {
                if (!"MESSAGES".equalsIgnoreCase(resultSet.getString("TABLE"))) {
                    continue;
                }
                Object[] columns = (Object[]) resultSet.getObject("COLUMNS");
                Object[] keys = (Object[]) resultSet.getObject("KEYS");
                if (columns == null || keys == null) {
                    continue;
                }
                for (int i = 0; i < columns.length && i < keys.length; i++) {
                    if ("ID".equalsIgnoreCase(String.valueOf(columns[i]))) {
                        messageIds.add(Long.parseLong(String.valueOf(keys[i])));
                    }
                }
            }
        }
        if (messageIds.isEmpty()) {
            return List.of();
        }
        String threadPlaceholders = String.join(", ", java.util.Collections.nCopies(threadIds.size(), "?"));
        String messagePlaceholders = String.join(", ", java.util.Collections.nCopies(messageIds.size(), "?"));
        var matched = new ArrayList<Long>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct thread_id
                from messages
                where thread_id in (%s)
                  and id in (%s)
                order by thread_id
                """.formatted(threadPlaceholders, messagePlaceholders))) {
            int index = 1;
            for (Long threadId : threadIds) {
                statement.setLong(index++, threadId);
            }
            for (Long messageId : messageIds) {
                statement.setLong(index++, messageId);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    private static List<Long> matchingMessageIdsForTokenRule(
            Connection connection,
            StoredTagRule rule,
            boolean unreadOnly) throws SQLException {
        if (!"subject".equals(rule.field()) && !"body".equals(rule.field())) {
            return matchingMessageIdsForColumnRule(connection, rule, "contains", unreadOnly);
        }
        var messageIds = new ArrayList<Long>();
        try (ResultSet resultSet = FullText.searchData(connection, rule.contains(), 0, 0)) {
            while (resultSet.next()) {
                if (!"MESSAGES".equalsIgnoreCase(resultSet.getString("TABLE"))) {
                    continue;
                }
                Object[] columns = (Object[]) resultSet.getObject("COLUMNS");
                Object[] keys = (Object[]) resultSet.getObject("KEYS");
                if (columns == null || keys == null) {
                    continue;
                }
                for (int i = 0; i < columns.length && i < keys.length; i++) {
                    if ("ID".equalsIgnoreCase(String.valueOf(columns[i]))) {
                        messageIds.add(Long.parseLong(String.valueOf(keys[i])));
                    }
                }
            }
        }
        if (messageIds.isEmpty()) {
            return List.of();
        }
        String placeholders = String.join(", ", java.util.Collections.nCopies(messageIds.size(), "?"));
        var matched = new ArrayList<Long>();
        String unreadClause = unreadOnly ? "and is_read = 0" : "";
        try (PreparedStatement statement = connection.prepareStatement("""
                select distinct id
                from messages
                where id in (%s)
                  %s
                order by id
                """.formatted(placeholders, unreadClause))) {
            int index = 1;
            for (Long messageId : messageIds) {
                statement.setLong(index++, messageId);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    matched.add(resultSet.getLong(1));
                }
            }
        }
        return matched;
    }

    static List<MailMessageSummary> loadThreadMessages(Connection connection, long threadId) throws SQLException {
        return loadThreadMessages(connection, List.of(threadId)).getOrDefault(threadId, List.of());
    }

    static Map<Long, List<MailMessageSummary>> loadThreadMessages(Connection connection, List<Long> threadIds) throws SQLException {
        var result = new LinkedHashMap<Long, List<MailMessageSummary>>();
        if (threadIds == null || threadIds.isEmpty()) {
            return result;
        }
        var orderedThreadIds = threadIds.stream()
                .filter(java.util.Objects::nonNull)
                .distinct()
                .toList();
        if (orderedThreadIds.isEmpty()) {
            return result;
        }
        List<StoredMessage> messages = new ArrayList<>();
        String placeholders = String.join(", ", java.util.Collections.nCopies(orderedThreadIds.size(), "?"));
        try (PreparedStatement statement = connection.prepareStatement("""
                select id, account_id, thread_id, internet_message_id, thread_key, folder_name, subject, from_name, from_email, to_summary,
                    sent_at, received_at, snippet, is_read
                from messages
                where thread_id in (%s)
                order by coalesce(received_at, sent_at, '') asc, id asc
                """.formatted(placeholders))) {
            for (int i = 0; i < orderedThreadIds.size(); i++) {
                statement.setLong(i + 1, orderedThreadIds.get(i));
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    messages.add(new StoredMessage(
                            resultSet.getLong(1),
                            resultSet.getString(2),
                            resultSet.getLong(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            resultSet.getString(8),
                            resultSet.getString(9),
                            resultSet.getString(10),
                            resultSet.getString(11),
                            resultSet.getString(12),
                            resultSet.getString(13),
                            resultSet.getInt(14) == 0));
                }
            }
        }
        var messagesByThreadId = new LinkedHashMap<Long, List<StoredMessage>>();
        for (Long threadId : orderedThreadIds) {
            messagesByThreadId.put(threadId, new ArrayList<>());
        }
        for (StoredMessage message : messages) {
            messagesByThreadId.computeIfAbsent(message.threadId(), ignored -> new ArrayList<>()).add(message);
        }
        for (Map.Entry<Long, List<StoredMessage>> entry : messagesByThreadId.entrySet()) {
            Map<String, Long> idsByInternetMessageId = new HashMap<>();
            for (StoredMessage message : entry.getValue()) {
                String internetMessageId = normalizeWhitespace(message.internetMessageId());
                if (!internetMessageId.isBlank()) {
                    idsByInternetMessageId.put(internetMessageId, message.id());
                }
            }
            var summaries = new ArrayList<MailMessageSummary>();
            for (StoredMessage message : entry.getValue()) {
                long parentMessageId = 0L;
                if (referenceKind(message.threadKey()) != ReferenceKind.NONE) {
                    parentMessageId = idsByInternetMessageId.getOrDefault(referencedMessageId(message.threadKey()), 0L);
                }
                summaries.add(new MailMessageSummary(
                        message.id(),
                        entry.getKey(),
                        parentMessageId,
                        message.subject(),
                        formattedFrom(message),
                        message.toSummary(),
                        message.effectiveTimestamp(),
                        message.snippet(),
                        message.unread()));
            }
            result.put(entry.getKey(), List.copyOf(summaries));
        }
        return result;
    }

    static void rebuildThreads(Connection connection, String accountId) throws SQLException {
        List<StoredMessage> rows = new ArrayList<>();
        try (PreparedStatement select = connection.prepareStatement("""
                select id, account_id, internet_message_id, thread_key, folder_name, subject, from_name, from_email, to_summary,
                    sent_at, received_at, snippet, is_read
                from messages
                where account_id = ?
                order by coalesce(received_at, sent_at, '') desc, id desc
                """)) {
            select.setString(1, accountId);
            try (ResultSet resultSet = select.executeQuery()) {
                while (resultSet.next()) {
                    rows.add(new StoredMessage(
                            resultSet.getLong(1),
                            resultSet.getString(2),
                            0L,
                            resultSet.getString(3),
                            resultSet.getString(4),
                            resultSet.getString(5),
                            resultSet.getString(6),
                            resultSet.getString(7),
                            resultSet.getString(8),
                            resultSet.getString(9),
                            resultSet.getString(10),
                            resultSet.getString(11),
                            resultSet.getString(12),
                            resultSet.getInt(13) == 0));
                }
            }
        }

        try (PreparedStatement deleteThreads = connection.prepareStatement("delete from threads where account_id = ?")) {
            deleteThreads.setString(1, accountId);
            deleteThreads.executeUpdate();
        }

        Map<String, StoredMessage> messagesByInternetId = new HashMap<>();
        for (StoredMessage row : rows) {
            String internetMessageId = normalizeWhitespace(row.internetMessageId());
            if (!internetMessageId.isBlank()) {
                messagesByInternetId.put(internetMessageId, row);
            }
        }

        Map<Long, String> resolvedThreadKeys = new HashMap<>();
        Map<String, List<StoredMessage>> grouped = new LinkedHashMap<>();
        for (StoredMessage row : rows) {
            String key = resolveThreadKey(row, messagesByInternetId, resolvedThreadKeys, new java.util.HashSet<>());
            grouped.computeIfAbsent(key, ignored -> new ArrayList<>()).add(row);
        }

        try (PreparedStatement updateMessageThread = connection.prepareStatement("""
                update messages
                set thread_id = ?
                where id = ?
                """)) {
            for (List<StoredMessage> group : grouped.values()) {
                group.sort(Comparator
                        .comparing(StoredMessage::effectiveTimestamp, Comparator.nullsFirst(Comparator.reverseOrder()))
                        .thenComparing(StoredMessage::id, Comparator.reverseOrder()));
                StoredMessage latest = group.getFirst();
                long threadId = insertStoredThread(connection, accountId, group, latest);
                for (StoredMessage message : group) {
                    updateMessageThread.setLong(1, threadId);
                    updateMessageThread.setLong(2, message.id());
                    updateMessageThread.addBatch();
                }
            }
            updateMessageThread.executeBatch();
        }
    }

    private static String resolveThreadKey(
            StoredMessage message,
            Map<String, StoredMessage> messagesByInternetId,
            Map<Long, String> resolvedThreadKeys,
            java.util.Set<Long> visiting) {
        String cached = resolvedThreadKeys.get(message.id());
        if (cached != null) {
            return cached;
        }
        if (!visiting.add(message.id())) {
            String cycleFallback = defaultThreadKey(message);
            resolvedThreadKeys.put(message.id(), cycleFallback);
            return cycleFallback;
        }
        String resolved = switch (referenceKind(message.threadKey())) {
        case NONE -> defaultThreadKey(message);
        case REPLY, REFERENCE -> {
            String referenceId = referencedMessageId(message.threadKey());
            if (referenceId.isBlank()) {
                yield defaultThreadKey(message);
            }
            StoredMessage parent = messagesByInternetId.get(referenceId);
            if (parent != null) {
                yield resolveThreadKey(parent, messagesByInternetId, resolvedThreadKeys, visiting);
            }
            yield "message-id:" + referenceId;
        }
        };
        visiting.remove(message.id());
        resolvedThreadKeys.put(message.id(), resolved);
        return resolved;
    }

    private static String defaultThreadKey(StoredMessage message) {
        String threadKey = message.threadKey();
        if (threadKey != null && !threadKey.isBlank()) {
            return threadKey;
        }
        String internetMessageId = normalizeWhitespace(message.internetMessageId());
        if (!internetMessageId.isBlank()) {
            return "message-id:" + internetMessageId;
        }
        return "message:" + message.id();
    }

    private static ReferenceKind referenceKind(String threadKey) {
        if (threadKey == null || threadKey.isBlank()) {
            return ReferenceKind.NONE;
        }
        if (threadKey.startsWith("reply:")) {
            return ReferenceKind.REPLY;
        }
        if (threadKey.startsWith("ref:")) {
            return ReferenceKind.REFERENCE;
        }
        return ReferenceKind.NONE;
    }

    private static String referencedMessageId(String threadKey) {
        int separator = threadKey == null ? -1 : threadKey.indexOf(':');
        if (separator < 0 || separator == threadKey.length() - 1) {
            return "";
        }
        return normalizeWhitespace(threadKey.substring(separator + 1));
    }

    private static long insertThread(
            Connection connection,
            String accountId,
            List<ImportedMailMessage> group,
            ImportedMailMessage latest) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into threads (
                    account_id, folder_name, subject, participants, snippet, last_message_at, unread_count, message_count
                ) values (?, ?, ?, ?, ?, ?, ?, ?)
                """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, accountId);
            statement.setString(2, latest.folderName());
            statement.setString(3, latest.subject());
            statement.setString(4, latest.participants());
            statement.setString(5, latest.snippet());
            statement.setString(6, latest.effectiveTimestamp());
            statement.setInt(7, (int) group.stream().filter(ImportedMailMessage::unread).count());
            statement.setInt(8, group.size());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getLong(1);
                }
            }
        }
        throw new SQLException("Failed to create thread for account " + accountId);
    }

    private static long insertStoredThread(
            Connection connection,
            String accountId,
            List<StoredMessage> group,
            StoredMessage latest) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into threads (
                    account_id, folder_name, subject, participants, snippet, last_message_at, unread_count, message_count
                ) values (?, ?, ?, ?, ?, ?, ?, ?)
                """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, accountId);
            statement.setString(2, latest.folderName());
            statement.setString(3, latest.subject());
            statement.setString(4, latest.participants());
            statement.setString(5, latest.snippet());
            statement.setString(6, latest.effectiveTimestamp());
            statement.setInt(7, (int) group.stream().filter(StoredMessage::unread).count());
            statement.setInt(8, group.size());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getLong(1);
                }
            }
        }
        throw new SQLException("Failed to create thread for account " + accountId);
    }

    private static Long updateExistingMessage(Connection connection, String accountId, ImportedMailMessage message)
            throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                update messages
                set thread_key = ?, folder_name = ?, subject = ?, from_name = ?, from_email = ?, to_summary = ?,
                    sent_at = ?, received_at = ?, snippet = ?, body_text = case when ? = '' then body_text else ? end,
                    is_read = ?
                where account_id = ? and internet_message_id = ?
                """);
                PreparedStatement query = connection.prepareStatement("""
                        select id
                        from messages
                        where account_id = ? and internet_message_id = ?
                        """)) {
            statement.setString(1, message.threadKey());
            statement.setString(2, message.folderName());
            statement.setString(3, message.subject());
            statement.setString(4, message.fromName());
            statement.setString(5, message.fromEmail());
            statement.setString(6, message.toSummary());
            statement.setString(7, message.sentAt());
            statement.setString(8, message.receivedAt());
            statement.setString(9, message.snippet());
            statement.setString(10, message.bodyText() == null ? "" : message.bodyText());
            statement.setString(11, message.bodyText());
            statement.setInt(12, message.unread() ? 0 : 1);
            statement.setString(13, accountId);
            statement.setString(14, message.internetMessageId());
            if (statement.executeUpdate() <= 0) {
                return null;
            }
            query.setString(1, accountId);
            query.setString(2, message.internetMessageId());
            try (ResultSet resultSet = query.executeQuery()) {
                return resultSet.next() ? resultSet.getLong(1) : null;
            }
        }
    }

    private static void insertMessage(Connection connection, ImportedMailMessage message) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into messages (
                    account_id, thread_id, thread_key, internet_message_id, folder_name, subject, from_name, from_email,
                    to_summary, sent_at, received_at, snippet, body_text, is_read
                ) values (?, null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, message.accountId());
            statement.setString(2, message.threadKey());
            statement.setString(3, message.internetMessageId());
            statement.setString(4, message.folderName());
            statement.setString(5, message.subject());
            statement.setString(6, message.fromName());
            statement.setString(7, message.fromEmail());
            statement.setString(8, message.toSummary());
            statement.setString(9, message.sentAt());
            statement.setString(10, message.receivedAt());
            statement.setString(11, message.snippet());
            statement.setString(12, message.bodyText());
            statement.setInt(13, message.unread() ? 0 : 1);
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    replaceMessageRecipients(connection, generatedKeys.getLong(1), message.recipients());
                }
            }
        }
    }

    private static void replaceMessageRecipients(
            Connection connection,
            long messageId,
            List<ImportedMailRecipient> recipients) throws SQLException {
        try (PreparedStatement delete = connection.prepareStatement("""
                delete from message_recipients
                where message_id = ?
                """)) {
            delete.setLong(1, messageId);
            delete.executeUpdate();
        }
        if (recipients == null || recipients.isEmpty()) {
            return;
        }
        var uniqueRecipients = new LinkedHashMap<String, ImportedMailRecipient>();
        for (ImportedMailRecipient recipient : recipients) {
            String normalizedEmail = recipient.normalizedEmail();
            if (normalizedEmail.isBlank()) {
                continue;
            }
            uniqueRecipients.putIfAbsent(recipient.normalizedType() + "|" + normalizedEmail, recipient);
        }
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into message_recipients (
                    message_id, recipient_type, recipient_name, recipient_email, recipient_email_lc
                ) values (?, ?, ?, ?, ?)
                """)) {
            for (ImportedMailRecipient recipient : uniqueRecipients.values()) {
                String normalizedEmail = recipient.normalizedEmail();
                insert.setLong(1, messageId);
                insert.setString(2, recipient.normalizedType());
                insert.setString(3, recipient.name());
                insert.setString(4, recipient.email());
                insert.setString(5, normalizedEmail);
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static String statusMessage(
            List<MailAccountSummary> accounts,
            List<MailThreadSummary> threads,
            EmailPaths paths) {
        List<String> statuses = accounts.stream()
                .map(MailAccountSummary::syncStatus)
                .filter(status -> status != null && !status.isBlank())
                .distinct()
                .toList();
        if (!statuses.isEmpty() && threads.isEmpty()) {
            return String.join("  |  ", statuses);
        }
        if (!threads.isEmpty()) {
            return "";
        }
        if (!accounts.isEmpty()) {
            return "No mail has been synced yet. Press r to refresh.";
        }
        return "Configure accounts in " + paths.accountsPath()
                + " and tag rules in " + paths.tagRulesPath()
                + ". Mail is stored in " + paths.databaseFilePath() + ".";
    }

    private static String snippet(String body) {
        if (body == null) {
            return "";
        }
        String normalized = normalizeWhitespace(body);
        return normalized.length() > 180 ? normalized.substring(0, 180) : normalized;
    }

    private static String recipientSummary(MailDraft draft) {
        var recipients = new ArrayList<String>();
        if (draft.to() != null && !draft.to().isBlank()) {
            recipients.add(normalizeWhitespace(draft.to()));
        }
        if (draft.cc() != null && !draft.cc().isBlank()) {
            recipients.add(normalizeWhitespace(draft.cc()));
        }
        if (draft.bcc() != null && !draft.bcc().isBlank()) {
            recipients.add(normalizeWhitespace(draft.bcc()));
        }
        return String.join(", ", recipients);
    }

    private static List<ImportedMailRecipient> recipients(MailDraft draft) {
        var recipients = new ArrayList<ImportedMailRecipient>();
        appendRecipients(recipients, "TO", draft.to());
        appendRecipients(recipients, "CC", draft.cc());
        appendRecipients(recipients, "BCC", draft.bcc());
        return List.copyOf(recipients);
    }

    private static void appendRecipients(List<ImportedMailRecipient> recipients, String type, String text) {
        if (text == null || text.isBlank()) {
            return;
        }
        var seen = new java.util.HashSet<String>();
        for (String part : text.split(",")) {
            String email = extractEmail(part);
            if (!email.isBlank() && seen.add(type + "|" + email.toLowerCase(java.util.Locale.ROOT))) {
                recipients.add(new ImportedMailRecipient(type, extractName(part), email));
            }
        }
    }

    private static String extractEmail(String value) {
        String text = normalizeWhitespace(value);
        int start = text.indexOf('<');
        int end = text.indexOf('>');
        if (start >= 0 && end > start) {
            return text.substring(start + 1, end).trim();
        }
        return text.contains("@") ? text : "";
    }

    private static String extractName(String value) {
        String text = normalizeWhitespace(value);
        int start = text.indexOf('<');
        if (start > 0) {
            return text.substring(0, start).trim();
        }
        return "";
    }

    private static String normalizeSubject(String subject) {
        if (subject == null) {
            return "";
        }
        return subject.strip().toLowerCase(java.util.Locale.ROOT);
    }

    private static String normalizeWhitespace(String text) {
        return text == null ? "" : text.replaceAll("\\s+", " ").trim();
    }

    private static String normalizeSearchQuery(String query) {
        return query == null ? "" : query.toLowerCase(java.util.Locale.ROOT).trim();
    }

    private static String normalizeField(String value) {
        return value == null || value.isBlank() ? "sender" : value.trim().toLowerCase(java.util.Locale.ROOT);
    }

    private static String normalizeMatch(String value) {
        return value == null || value.isBlank() ? "contains" : value.trim().toLowerCase(java.util.Locale.ROOT);
    }

    private static String formattedFrom(StoredMessage message) {
        String display = message.fromName();
        String email = message.fromEmail();
        if (display != null && !display.isBlank() && email != null && !email.isBlank()) {
            return display + " <" + email + ">";
        }
        if (display != null && !display.isBlank()) {
            return display;
        }
        return email == null ? "" : email;
    }

    private static int countThreads(
            Connection connection,
            String query,
            boolean includeTagMatch,
            ThreadQueryFilter filter) throws SQLException {
        StringBuilder sql = new StringBuilder("select count(*) from threads t\n");
        sql.append("join accounts a on a.id = t.account_id\n");
        String whereClause = threadWhereClause("t", "a", query, includeTagMatch, filter);
        if (!whereClause.isBlank()) {
            sql.append("where ").append(whereClause);
        }
        try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
            bindThreadParameters(statement, 1, query, includeTagMatch, filter);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next() ? resultSet.getInt(1) : 0;
            }
        }
    }

    private static String threadWhereClause(
            String threadAlias,
            String accountAlias,
            String query,
            boolean includeTagMatch,
            ThreadQueryFilter filter) {
        var clauses = new ArrayList<String>();
        if (query != null && !query.isBlank()) {
            clauses.add(threadSearchPredicate(threadAlias, includeTagMatch));
        }
        String filterPredicate = filter == null ? "" : filter.predicateSql();
        if (!filterPredicate.isBlank()) {
            clauses.add(filterPredicate);
        }
        return String.join("\n  and ", clauses);
    }

    private static ThreadQueryFilter threadQueryFilter(Connection connection, MailThreadFilter filter) throws SQLException {
        MailThreadFilter effectiveFilter = filter == null ? MailThreadFilter.all() : filter;
        return switch (effectiveFilter.kind()) {
        case ALL -> ThreadQueryFilter.none();
        case ACCOUNT -> new ThreadQueryFilter("t.account_id = ?", List.of(effectiveFilter.value()));
        case TAG -> tagThreadQueryFilter(connection, effectiveFilter.value());
        case UNSORTED -> new ThreadQueryFilter("""
                (
                    %1$s
                    or not exists (
                        select 1
                        from tag_rules tr
                        where %2$s
                    )
                )
                """.formatted(threadAddressedToAccountSql("t", "a"), threadHasAnyTagSql("t")), List.of());
        };
    }

    private static String threadHasAnyTagSql(String threadAlias) {
        return """
                exists (
                    select 1
                    from messages tm
                    where tm.thread_id = %1$s.id
                      and %2$s
                )
                """.formatted(threadAlias, nonTokenRuleMatchesMessageSql("tm"));
    }

    private static ThreadQueryFilter tagThreadQueryFilter(Connection connection, String tagName) throws SQLException {
        List<StoredTagRule> rules = loadTagRules(connection, tagName);
        if (rules.isEmpty()) {
            return new ThreadQueryFilter("1 = 0", List.of());
        }
        var threadIds = new LinkedHashSet<Long>();
        for (StoredTagRule rule : rules) {
            threadIds.addAll(matchingThreadIdsForRule(connection, rule));
        }
        if (threadIds.isEmpty()) {
            return new ThreadQueryFilter("1 = 0", List.of());
        }
        String placeholders = String.join(", ", java.util.Collections.nCopies(threadIds.size(), "?"));
        return new ThreadQueryFilter("t.id in (" + placeholders + ")", new ArrayList<>(threadIds));
    }

    private static String threadSearchPredicate(String threadAlias, boolean includeTagMatch) {
        String base = """
                (
                    lower(coalesce(%1$s.subject, '')) like ?
                    or lower(coalesce(%1$s.participants, '')) like ?
                    or lower(coalesce(%1$s.snippet, '')) like ?
                    or exists (
                        select 1
                        from messages m
                        where m.thread_id = %1$s.id
                          and (
                              lower(coalesce(m.subject, '')) like ?
                              or lower(coalesce(m.from_name, '')) like ?
                              or lower(coalesce(m.from_email, '')) like ?
                              or lower(coalesce(m.to_summary, '')) like ?
                              or lower(coalesce(m.snippet, '')) like ?
                              or lower(coalesce(m.body_text, '')) like ?
                          )
                    )
                """.formatted(threadAlias);
        if (!includeTagMatch) {
            return base + "\n)";
        }
        return base + """
                    or exists (
                        select 1
                        from tag_rules tr
                        join messages tm on tm.thread_id = %1$s.id
                        where lower(coalesce(tr.tag_name, '')) like ?
                          and (
                              (tr.field_name = 'recipient' and lower(coalesce(tm.to_summary, '')) like '%%' || lower(tr.contains_value) || '%%')
                              or (tr.field_name = 'subject' and lower(coalesce(tm.subject, '')) like '%%' || lower(tr.contains_value) || '%%')
                              or (tr.field_name = 'body' and lower(coalesce(tm.body_text, '')) like '%%' || lower(tr.contains_value) || '%%')
                              or ((tr.field_name = 'sender' or tr.field_name is null or tr.field_name = '') and lower(coalesce(tm.from_email, '')) like '%%' || lower(tr.contains_value) || '%%')
                          )
                    )
                )
                """.formatted(threadAlias);
    }

    private enum ReferenceKind {
        NONE,
        REPLY,
        REFERENCE
    }

    private static int bindThreadParameters(
            PreparedStatement statement,
            int index,
            String query,
            boolean includeTagMatch,
            ThreadQueryFilter filter) throws SQLException {
        if (query != null && !query.isBlank()) {
            index = bindSearchParameters(statement, index, query, includeTagMatch);
        }
        if (filter != null) {
            for (Object value : filter.params()) {
                if (value instanceof Long longValue) {
                    statement.setLong(index++, longValue);
                } else {
                    statement.setString(index++, String.valueOf(value));
                }
            }
        }
        return index;
    }

    private static int bindSearchParameters(PreparedStatement statement, int index, String query, boolean includeTagMatch)
            throws SQLException {
        String like = "%" + query + "%";
        for (int i = 0; i < (includeTagMatch ? 10 : 9); i++) {
            statement.setString(index++, like);
        }
        return index;
    }

    private static boolean hasMatchingTagName(Connection connection, String query) throws SQLException {
        if (query == null || query.isBlank()) {
            return false;
        }
        try (PreparedStatement statement = connection.prepareStatement("""
                select 1
                from tag_rules
                where lower(coalesce(tag_name, '')) like ?
                fetch first 1 rows only
                """)) {
            statement.setString(1, "%" + query + "%");
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next();
            }
        }
    }

    private static void ensureFullTextIndex(Connection connection) throws SQLException {
        FullText.init(connection);
        try {
            FullText.createIndex(connection, "PUBLIC", "MESSAGES", "SUBJECT, BODY_TEXT");
        } catch (SQLException e) {
            String message = e.getMessage();
            if (message == null || !message.contains("FT.INDEXES")) {
                throw e;
            }
        }
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.execute();
        }
    }
}
